const data = {
  products: [
    {
      name: 'Watch',
      slug: 'watch-7',
      category: 'accessories',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple watch 7 nike',
    },
    {
      name: 'Watch',
      slug: 'watch-7-nike',
      category: 'accessories',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple watch 7',
    },
    {
      name: 'Watch',
      slug: 'watch-6',
      category: 'accessories',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple watch 6 nike',
    },
    {
      name: 'Watch',
      slug: 'watch-se',
      category: 'accessories',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'Apple watch SE nike',
    },
  ],
};

export default data;
